api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)

urlpatterns = [
    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getProject),

    path('users/token/', 
         TokenObtainPairView.as_view(), 
         name='token_obtain_pair'),

    path('users/token/refresh/', 
         TokenRefreshView.as_view(), 
         name='token_refresh'),

    path('remove-module/', views.removeModule),
]

users/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('login', views.loginUser, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('register', views.registerUser, name='register'),
    
    
    path('', views.profiles, name='profiles'),
    path('user-profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('update-profile/', views.updateProfile,  name='update-profile'),
    
    path('account/', views.userAccount, name='account'),


    path('create-hobby/', views.createHobby, name='create-hobby'),
    path('update-hobby/<str:pk>/', views.updateHobby, name='update-hobby'),    
    path('delete-hobby/<str:pk>/', views.deleteHobby, name='delete-hobby'),

    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='message'),
    path('create-message/<str:pk>/', views.createMessage, name='create-message'),
    path('reply-message/<str:pk>/', views.replyMessage, name='reply-message'),
        
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


# Create your models here.
class Profile(models.Model):
    JOB_TYPE = (
        ('student', '學生'),
        ('employed', '在職'),
        ('other', '其他'),
    )

    user = models.OneToOneField( User,
                                 on_delete=models.CASCADE,
                                 null=True,
                                 blank=True )
                                 
    name = models.CharField( max_length=100,
                             blank=True,
                             null=True )
    email = models.EmailField( max_length=200,
                               blank=True,
                               null=True )
    username = models.CharField( max_length=200,
                                 blank=True,
                                 null=True )
    bio = models.TextField( blank=True,
                            null=True )
    profile_image = models.ImageField( blank=True,
                                       null=True,
                                       upload_to="profiles/",
                                       default = 'profiles/user-default.png' )
    social_facebook = models.CharField( max_length=200,
                                        blank=True,
                                        null=True )
    location = models.CharField( max_length=100, 
                                 blank=True,
                                 null=True,
                                 default="Taiwan" )
    background = models.CharField( max_length=200,
                                   blank=True,
                                   null=True )

    job = models.CharField( max_length=100,
                            choices=JOB_TYPE,
                            default="other" )

    is_host = models.BooleanField( default=False )

    group_id = models.CharField( max_length=200,
                                 default=None,
                                 blank=True,
                                 null=True )

    created = models.DateTimeField( auto_now_add=True )
    id = models.UUIDField( default=uuid.uuid4,
                           unique=True,
                           primary_key=True,
                           editable=False )
    
    def __str__(self):
        return self.user.username


    @property
    def imageURL(self):
        try: 
            url = self.profile_image.url
        except:
            url = '/images/profiles/user-default.png'
        return url


class Hobby(models.Model):
    owner = models.ForeignKey(Profile, 
                              on_delete=models.CASCADE,
                              null=True, 
                              blank=True)
    name = models.CharField(max_length=200,
                            blank=True,
                            null=True)
    description = models.TextField(blank=True, 
                                   null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField( default=uuid.uuid4,
                           unique=True,
                           primary_key=True,
                           editable=False)
    def __str__(self):
        return str(self.name)


class Message(models.Model):
    sender = models.ForeignKey( Profile, 
                                on_delete=models.SET_NULL,
                                null=True,
                                blank=True )
    recipient = models.ForeignKey( Profile, 
                                   on_delete=models.CASCADE,
                                   related_name='messages' )
    name = models.CharField( max_length=200,
                             null=True, 
                             blank=True )
    email = models.EmailField( max_length=200,
                               null=True,
                               blank=True )
    subject = models.CharField( max_length=200,
                                null=True,
                                blank=True )
    body = models.TextField()
    is_read = models.BooleanField( default=False,
                                   null=True )
    is_apply_related = models.BooleanField( default=False )
    created = models.DateTimeField( auto_now_add=True )
    id = models.UUIDField( default=uuid.uuid4,
                           primary_key=True,
                           unique=True,
                           editable=False )

    def __str__(self) -> str:
        return self.subject

    class Meta:
        ordering = ['is_read', "-is_apply_related", '-created']

users/views.py
from django.contrib.messages.api import MessageFailure
from django.shortcuts import redirect, render

from .models import Profile, Message
from projects.models import  Group


from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .form import CustomerUserCreationForm, MessageForm, ProfileForm, HobbyForm
from . import utils

def registerUser(request):
    page = 'register'
    form = CustomerUserCreationForm()

    if request.method == 'POST':
        form = CustomerUserCreationForm(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            messages.success(request, f'Welcome to the ccPartner, {user}')
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, "An error has occured during register...")
    
    context = {
        'form':form,
        'page':page,
    }
    return render(request, 'users/login-register.html', context=context)



def loginUser(request):
    if request.user.is_authenticated:
        return redirect('profiles')
    
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate( request, 
                             username=username, 
                             password=password )

        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'account')

        else:
            messages.error(request, 'Username OR password is incorrect')

    return render(request, 'users/login-register.html')

        

def logoutUser(request):
    logout(request)
    messages.success(request, 'User logout')
    return redirect('login')




def profiles(request):
    profiles, search_query = utils.searchProfiles(request)
    custom_range, profiles = utils.paginateProfile(request, profiles, 9)

    context = {
        "profiles":profiles,
        "search_query": search_query,
        "custom_range":custom_range,
    }

    return render(request, 'users/profiles.html', context=context)


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)
    topHobbies = profile.hobby_set.exclude(description__exact='')
    otherHobbies = profile.hobby_set.filter(description__exact='')
    context = {
        "profile":profile,
        'topHobbies': topHobbies,
        'otherHobbies': otherHobbies,
    }

    return render(request, 'users/user-profile.html', context=context)


@login_required(login_url='login')
def userAccount(request):
    profile = request.user.profile
    if profile.group_id:
        group = Group.objects.get(id=profile.group_id)
        project = group.project
    else:
        group, project = None, None


    context = {
        'profile':profile,
        'group': group,
        'project': project,
    }
    
    return render(request, 'users/account.html', context=context)


@login_required(login_url='login')
def updateProfile(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        if len(request.FILES):
            if not "user-default" in profile.imageURL:
                profile.profile_image.delete(save=True)

        form = ProfileForm(request.POST, 
                           request.FILES,
                           instance=profile)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Profile is updated successfully!')
            return redirect('account')
    
        else:
            messages.error(request, "Please check the fields in your profile form again...")
    
    context = {
        'form':form,
    }

    return render(request, 'users/profile_form.html', context=context)
    

@login_required(login_url='login')
def createHobby(request):
    profile = request.user.profile
    form = HobbyForm()

    if request.method == "POST":
        form =  HobbyForm(request.POST)
        if form.is_valid():
            hobby = form.save(commit=False)
            hobby.owner = profile
            hobby.save()

            messages.success(request, 'Hobby was created successfully!')
            return redirect('account')
    
    context = {
        'form':form,
    }

    return render(request, 'users/hobby_form.html', context=context)


@login_required(login_url='login')
def updateHobby(request, pk):
    profile = request.user.profile
    hobby = profile.hobby_set.get(id=pk)
    form = HobbyForm(instance=hobby)

    if request.method == "POST":
        form = HobbyForm(request.POST, instance=hobby)
        if form.is_valid():
            form.save()
            messages.success(request, 'Hobby was updated successfully!')

            return redirect('account')

    context = {
        "form":form,
    }
    return render(request, 'users/hobby_form.html', context=context)

@login_required(login_url='login')
def deleteHobby(request, pk):
    profile = request.user.profile
    hobby = profile.hobby_set.get(id=pk)

    if request.method == "POST":
        hobby.delete()
        messages.success(request, 'Hobby was deleted successfully')

        return redirect('account')
    
    context = {
        "hobby":hobby,
    }
    return render(request, 'users/delete-hobby.html', context=context)


@login_required(login_url='login')
def inbox(request):
    profile = request.user.profile
    messageRequest = profile.messages.all()

    unreadCount = messageRequest.filter(is_read__in = ['False']).count()
    context = {
        "messageRequests": messageRequest, 
        "unreadCount":unreadCount,
    }

    return render(request, 'users/inbox.html', context=context)



@login_required(login_url='login')
def viewMessage(request, pk):
    profile = request.user.profile
    messageRequest = profile.messages.get(id=pk)

    if request.method == "POST":
        messageRequest.delete()
        messages.success(request, 'Message Deleted.')
        return redirect('inbox')

    if not messageRequest.is_read:
        messageRequest.is_read = True
        messageRequest.save()
    
    
    context = {
        "message": messageRequest,
    }

    return render(request, 'users/message.html', context=context)

def createMessage(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profile
    except: 
        sender = None

    if request.method == "POST":
        form = MessageForm(request.POST)

        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient
            
            if sender:
                message.email = sender.email
                message.name = sender.username
            
            message.save()
            messages.success(request, "Your message was successfully sent!")
            
            if 'next' in request.GET:
                return redirect('project', pk=request.GET["next"])
            else:
                return redirect('user-profile', pk=recipient.id)
    
    context={
        'form':form,
        'recipient':recipient,
    }
    return render(request, 'users/message-form.html', context=context)


@login_required(login_url='login')
def replyMessage(request, pk):
    targetMessage = Message.objects.get(id=pk)
    if "Re: " in targetMessage.subject:
        subject = targetMessage.subject
    else:
        subject = f'Re: {targetMessage.subject}'
    form = MessageForm(
        initial = {'subject':subject}
    )

    if request.method == "POST":
        form = MessageForm(request.POST)

        if form.is_valid():
            message = form.save(commit=False)
            sender = request.user.profile
            
            message.sender = sender
            message.recipient = targetMessage.sender
            message.email = sender.email
            message.name = sender.username

            message.save()
            messages.success(request, f"You've successfully replied the sender {targetMessage.sender}")

            return redirect('inbox')

    context = {
        'form': form,
    }
    return render(request, 'users/message-form.html', context=context)

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
User Account
{% endblock %}

{% block content %}

<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-profile' %}"><i class="im im-edit"></i> Edit</a>
            <img class="avatar avatar--xl dev__avatar" src="{{ profile.imageURL }}" />
            <h2 class="dev__name">{{ profile.username }}</h2>
            <!-- <p class="dev__title">{{ profile.get_job_display }}</p> -->
            <p class="dev__title">{{ profile.job }}</p>
            <p class="dev__location">Based in {{ profile.location }}</p>
            <ul class="dev__social">
              {% if profile.social_facebook %}
              <li>
                <a title="Personal Website" href="{{ profile.social_facebook }}" target="_blank"><i class="im im-facebook"></i></a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>

      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">Background</h3>
          <p class="devInfo__about">
            {{ profile.background }}
          </p>
        </div>

        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}
            </p>
          </div>

        <!-- Hobby section -->
         <div class="settings">
          <h3 class="settings__title">Hobby</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-hobby' %}"><i class="im im-plus"></i> Add Hobby</a>
        </div>

        <table class="settings__table">
          {% for hobby in profile.hobby_set.all %}
          <tr>
            <td class="settings__tableInfo">
              <h4>{{ hobby.name }}</h4>
              <p>
                {{ hobby.description }}
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-hobby' hobby.id %}"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-hobby' hobby.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          {% endfor %}
          
        </table>
        <!-- End of Hobby section -->


        <!-- Project section --> 
        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          {% if not profile.group_id %}
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
          {% endif %}
        </div>

        
        <table class="settings__table">
          {% if project %}
          <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'project' project.id %}"><img src="{{ project.imageURL }}" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'project' project.id %}">{{ project.title }}</a>
              <p>
                {{ project.description|slice:'50' }}
              </p>
            </td>
            <td class="settings__tableActions">
              {% if profile.is_host %}
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
              {% endif %}
            </td>
          </tr>
          {% else %}
          <tr>
            <td class="settings__thumbnail">
              <a href="#"><img src="{% static 'images/no-project.jpg' %}" alt='no proj'/></a>
            </td>
            <td class="settings__tableInfo">
              <h5>You havn't attend any project yet.</h5>
            </td>
          </tr>
          {% endif %}
        </table>
        <!-- end of project section -->

        <!-- Group Member Section -->
        {% if group %}
        <div class="settings">
          <h3 class="settings__title">Team Members</h3>
          {% if not profile.is_host %}
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'quit-team' %}?next=/account"><i class="im im-minus"></i> Quit team</a>
          {% endif %}
        </div>

        <!-- Member list -->
        <table class="settings__table">
          <!-- Host -->
          {% if not profile.is_host %}
          <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'user-profile' project.owner.id %}"><img src="{{ project.owner.imageURL }}" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'user-profile' project.owner.id %}">{{ project.owner.username }} (Host)</a>
              <p>
                {{ project.owner.bio|slice:'50' }}
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'create-message' project.owner.id  %}" ><i class="im im-edit"></i>Message</a>
            </td>
          </tr>
          {% endif %}

          {% for member in group.members %}
          {% if member != profile %}
          <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'user-profile' member.id %}"><img src="{{ member.imageURL }}" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'user-profile' member.id %}">{{ member.username }}</a>
              <p>
                {{ member.bio|slice:'50' }}
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'create-message' member.id %}" ><i class="im im-edit"></i>Message</a>
              {% if profile.is_host %}
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'remove-member' member.id %}"><i class="im im-x-mark-circle-o"></i>
                Remove</a>
              {% endif %}
            </td>
          </tr>
          {% endif %}
          {% endfor %}
        </table>
        
        {% endif %} <!-- end of group -->


      </div>
    </div>
  </div>
</main>

{% endblock %}

users/templates/users/delete-hobby.html
{% extends 'main.html' %}

{% block title %}
Delete Hobby
{% endblock %}

{% block content %}
    
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    <p>Are your sure you want to delete <strong>{{ hobby }}</strong>?</p>
                    <a class="btn btn--sub btn--lg  my-md" href="{{ request.GET.next }}">&#x2190 Go Back</a>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Confirm" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/hobby_form.html
{% extends 'main.html' %}

{% block title %}
Edit Hobby
{% endblock %}


{% block content %}
    <!-- <h1>Creat Skill</h1>

    <form method='POST'>
        {% csrf_token %}
        {% for field in form %}
            {{field.label}}
            {{field}}
        {% endfor %}
        <input type="submit" value="Submit"/>
    </form> -->

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}

                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}
{% load static %}
{% block title %}
Message Inbox
{% endblock %}

{% block content %}
<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>

    {% if messageRequests %}
    <ul class="messages">
      {% for message in messageRequests %}  
      {% if message.is_read == False %}
      <li class="message message--unread">
        {% else %}
      <li class="message">
        {% endif %}

        <a href="{% url 'message' message.id %}">
          <span class="message__author">{{message.name}}</span>
          <span class="message__subject">{{message.subject}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <table class="settings__table">
      <tr>
            <td class="settings__thumbnail">
              <a href="#"><img src="{% static 'images/no-message.jpg' %}" alt='no msg'/></a>
            </td>
            <td class="settings__tableInfo">
              <h5>~Your message box is empty~</h5>
            </td>
          </tr>
    </table>
    {% endif %}
  </div>
</main>

{% endblock content %}

users/templates/users/login-register.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
Login
{% endblock %}


{% block content %}
<body>
{% if page == 'register' %}

  <div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account SignUp</h3>
        <p>Create a new developer account</p>
      </div>

      <form action="{% url 'register' %}" class="form auth__form" method="POST">
        {% csrf_token %}
        
        {% for field in form %}
            
            <div class="form__field">
                <label for="formInput#text">{{ field.label }}</label>
                {{ field }}

                {% if field.help_text  %}
                    <small>{{ field.help_text }}</small>
                {% endif %}

                {% for error in field.errors %}
                    <p style="color:red;">{{ error }}</p>
                {% endfor %}

          </div>

        {% endfor %}

        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
        </div>
      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="login.html">Log In</a>
      </div>
    </div>
  </div>



{% else %}
  
    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account Login</h3>
          <p>Hello Developer, Welcome Back!</p>
        </div>

        <form action="" class="form auth__form" method="POST">
          {% csrf_token %}
           <!-- Input:username -->
          <div class="form__field">
            <label for="formInput#text">Username: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="username"
              placeholder="Enter your username..."
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            <a href="{% url 'reset_password' %}">Forget Password?</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'register' %}">Sign Up</a>
        </div>
      </div>
    </div>

{% endif %}

</body>
{% endblock %}

users/templates/users/message-form.html
{% extends 'main.html' %}

{% block title %}
Edit Message to {{ recipient.username }}
{% endblock %}

{% block content %}

  <main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            {% if recipient %}
            <a href="{% url 'user-profile' recipient.id %}" 
               class="backButton">
               <i class="im im-angle-left"></i>
            </a>
            {% else %}
            <a href="{% url 'inbox' %}" 
               class="backButton">
               <i class="im im-angle-left"></i>
            </a>
            {% endif %}
            <br/>

            <form class="form" method="POST">
            {% csrf_token %}
            {% if request.user.is_authenticated == False %}
              <!-- NAME field -->
              <div class="form__field">
                <label for="formInput#text">
                  {{ form.name.label }}
                </label>
                {{ form.name }}
              </div>

              <!-- EMAIL field -->
              <div class="form__field">
                <label for="formInput#text">
                  {{ form.email.label }}
                </label>
                {{ form.email }}
              </div>
            {% endif %}

              <!-- SUBJECT -->
              <div class="form__field">
                <label for="formInput#text">
                  {{ form.subject.label }}
                </label>
                {{ form.subject }}
              </div>

              <!-- BODY -->
              <div class="form__field">
                <label for="formInput#text">
                  {{ form.body.label }}
                </label>
                {{ form.body }}
              </div>
            
              <input type="submit" 
                     value="Submit" 
                     class="btn btn--sub btn--lg my-md">
            </form>
        </div>
    </div>

  </main>

{% endblock %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block title %}
Message from {{ message.sender }}
{% endblock %}

{% block content %}

  <main class="messagePage my-xl">
    <div class="content-box">
        <div class="message">
            <a href="{% url 'inbox' %}" class="backButton">
                <i class="im im-angle-left"></i>
            </a>
            <h2 class="message__subject">{{ message.subject }}</h2>
            <a href="{% url 'user-profile' message.sender.id %}" 
               class="message__author">
                {{ message.sender }}
            </a>
            <p class="message__date">
                {{ message.created }}
            </p>
            <div class="message__body">
                {{ message.body | linebreaksbr }}
            </div>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {% if not message.is_apply_related %}
                <a class="btn btn--sub btn--lg  my-md" href="{% url 'reply-message' message.id %}">Reply</a>
                {% endif %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Delete" />
            </form>
        </div>
    </div>
  </main>

{% endblock %}

users/templates/users/profile_form.html
{% extends 'main.html' %}

{% block title %}
Update Profile
{% endblock %}

{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form action="{% url 'update-profile' %}" method='POST', enctype="multipart/form-data">
            {% csrf_token %}
                {% for field in form %}
                
                <div class="form__field">
                    <label for="formInput#text">{{ field.label }}</label>
                    {{ field }}
                </div>

                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock %}