api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)

urlpatterns = [
    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getProject),

    path('users/token/', 
         TokenObtainPairView.as_view(), 
         name='token_obtain_pair'),

    path('users/token/refresh/', 
         TokenRefreshView.as_view(), 
         name='token_refresh'),

    path('remove-module/', views.removeModule),
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projects, name='projects'),
    path('project/<str:pk>/', views.project, name='project'),
    path('create-project/', views.createProject, name='create-project'),
    path('update-project/<str:pk>/', views.updateProject, name="update-project"),
    path('delete-project/<str:pk>/', views.deleteProject, name='delete-project'),

    path('remove-member/<str:pk>/', views.removeMember, name='remove-member'),
    path('quit-team/', views.quitTeam, name="quit-team"),

    path('apply/<str:pk>/', views.apply, name='apply'),
    path('apply-box/', views.applyBox, name='apply-box'),
    path('verify-apply/<str:pk>/', views.verifyApply, name='verify-apply'),
    path('verify-quit/<str:pk>/', views.verifyQuit, name='verify-quit'),
]

projects/models.py
from django.db import models
from django.db import models

from users.models import Profile
import uuid
# Create your models here.

class Project(models.Model):

    FEATURE_TYPE = (
        ("delicacy", "美食評鑑"),
        ("finance", "投資理財"),
        ("sport", '運動健身') ,
        ("pet", "寵物生活"),
        ("toolkit", "輔助工具"),
        ("society", "社會政治"),
        ("shopping", "購物達人"),
        ("entertainment","音樂電影"),
        ("other","其他"),
    )

    owner = models.ForeignKey( Profile,
                               on_delete=models.CASCADE,
                               default=None,
                               null=True,
                               blank=True )
                               
    title = models.CharField( max_length=100 )
    description = models.TextField( null=True,
                                    blank=True )
    featured_image = models.ImageField( null=True,
                                        blank=True,
                                        default='default.jpg' )
    modules = models.ManyToManyField( "Module", 
                                      blank=True,
                                      null=True, )

    types = models.ManyToManyField( "Type", 
                                   blank=True,
                                   null=True,
                                   default=None )

    feature = models.CharField( max_length=20,
                                choices=FEATURE_TYPE,
                                default=FEATURE_TYPE[-1][0] )

    is_active = models.BooleanField( default=True )

    id = models.UUIDField( default=uuid.uuid4,
                           unique=True,
                           primary_key=True,
                           editable=False )
    created = models.DateTimeField( auto_now_add=True )


    class Meta:
        ordering = ['created']

    def __str__(self) -> str:
        return self.title

    @property 
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = '/images/default.jpg'
        return url




class Module(models.Model):
    name = models.CharField(max_length=100)
    id = models.UUIDField( default=uuid.uuid4,
                           unique=True,
                           primary_key=True,
                           editable=False )
    created = models.DateTimeField( auto_now_add=True )
    
    def __str__(self) -> str:
        return self.name



class Type(models.Model):
    name = models.CharField(max_length=100)
    id = models.UUIDField( default=uuid.uuid4,
                           unique=True,
                           primary_key=True,
                           editable=False )
    created = models.DateTimeField( auto_now_add=True )
    
    def __str__(self) -> str:
        return self.name



class Group(models.Model):

    project = models.OneToOneField( Project, 
                                    on_delete=models.CASCADE)
    member_1 = models.ForeignKey( Profile,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  blank=True,
                                  default=None,
                                  related_name='member_1')
    member_2 = models.ForeignKey( Profile,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  blank=True,
                                  default=None,
                                  related_name='member_2')                                                          
    member_3 = models.ForeignKey( Profile,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  blank=True,
                                  default=None,
                                  related_name='member_3')

    is_full = models.BooleanField( default=False )

    id = models.UUIDField( default=uuid.uuid4,
                           unique=True,
                           primary_key=True,
                           editable=False )
    created = models.DateTimeField( auto_now_add=True )


    def __str__(self) -> str:
        return self.project.title

    class Meta: 
        ordering = ['created']


    def addMember(self, profile):
        if not self.member_1:
            self.member_1 = profile
        elif not self.member_2:
            self.member_2 = profile
        else:
            self.member_3 = profile
        self.check_is_full()
        self.save()


    def removeMember(self, profile):
        if self.member_1 == profile:
            self.member_1 = None
        elif self.member_2 == profile:
            self.member_2 = None
        elif self.member_3 == profile:
            self.member_3 = None
        self.check_is_full()
        self.save()

        project = self.project
        project.is_active = True
        project.save()

        profile.group_id = None
        profile.save()

        return



    def check_is_full(self):
        if self.member_1 and self.member_2 and self.member_3:
            self.is_full = True
            # if group is full, hide the project for project list
            project = self.project
            project.is_active = False
            
            project.save()
            
        else:
            self.is_full = False
            
        self.save()

    @property
    def members(self):
        member_list = list()
        if self.member_1:
            member_list.append(self.member_1)
        if self.member_2:
            member_list.append(self.member_2)
        if self.member_3:
            member_list.append(self.member_3)
        return member_list




class Application(models.Model):
    group = models.ForeignKey( Group,
                               on_delete=models.CASCADE )
    sender = models.ForeignKey( Profile,
                                on_delete=models.CASCADE )
    is_apply = models.BooleanField( blank=True, 
                                    null=True )
    id = models.UUIDField( default=uuid.uuid4,
                           primary_key=True,
                           unique=True,
                           editable=False )
    created = models.DateTimeField( auto_now_add=True )

    def __str__(self):
        return f'{self.sender} apply for {self.group.project}'

projects/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from . import utils

from django.contrib.auth.decorators import login_required



# Create your views here.

def projects(request):
    projects, search_query = utils.searchProjects(request)
    custom_range, projects = utils.paginateProject(request, projects, 6)

    context = {
        "projects":projects,
        "search_query": search_query,
        'custom_range': custom_range,
    }

    return render(request, "projects/projects.html", context=context)


def project(request, pk):
    projObj = Project.objects.get(id=pk)
    
    context = {
        "project": projObj,
    }

    return render(request, "projects/project.html", context=context)



@login_required(login_url='login')
def createProject(request):
    profile = request.user.profile
    form = ProjectForm()

    if request.method == "POST":
        newModules = request.POST.get('newmodules').replace(',', ' ').split()
        newModules = list(map(str.capitalize, newModules))
        print(newModules)
        form = ProjectForm(request.POST, request.FILES)
        
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = profile
            project.save()
            profile.is_host = True

            for module in newModules:
                moduleObj, created = Module.objects.get_or_create(name=module)
                project.modules.add(moduleObj)
            
            form.save_m2m()
            
            
            
            return redirect('project', project.id)
    else:
        print("Error in creating Project")

    context = {
        "form":form,
    }
    return render(request, 'projects/project_form.html', context=context)


@login_required(login_url='login')
def updateProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    form = ProjectForm(instance=project)

    if request.method == "POST":
        newModules = request.POST.get('newmodules').replace(',', ' ').split()
        newModules = list(map(str.capitalize, newModules))

        # check if new image is uploaded
        if len(request.FILES):
            if not "default.jpg" in project.imageURL:
                project.featured_image.delete(save=True)

        form = ProjectForm(request.POST, request.FILES, instance=project)
        
        if form.is_valid():
            project = form.save()

            for module in newModules:
                moduleObj, created = Module.objects.get_or_create(name=module)
                project.modules.add(moduleObj)
            
            return redirect('project', pk=project.id)
        else:
            print('Error in Update Project...')
    
    context = {
        "form":form,
        "project": project,
    }
    return render(request, "projects/project_form.html", context=context)


@login_required(login_url='login')
def deleteProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)

    if request.method == "POST":
        project.featured_image.delete(save=True)
        project.delete()
        messages.success(request, 'Project was deleted successfully')
        return redirect('account')
    
    context = {
        "project":project,
    }

    return render(request, 'projects/delete-template.html', context=context)



@login_required(login_url='login')
def removeMember(request, pk):
    member = Profile.objects.get(id=pk)
    group_id = request.user.profile.group_id
    group = Group.objects.get(id=group_id)

    if request.method == "POST":
        group.removeMember(member)
        utils.NotificationMessage(
            sender = request.user.profile, 
            recipient = member, 
            subject = "Project quit notification.", 
            body = f"This message is sent by system.\nYou've been removed from team of project: {group.project} by host.",
            )
        messages.success(request, f"You've kiced the memeber {member.username} out!")

    
        return redirect('account')
    
    context = {
        'member':member,
    }

    return render(request, 'projects/delete-template.html', context=context)



@login_required(login_url='login')
def quitTeam(request):
    profile = request.user.profile
    group = Group.objects.get(id=profile.group_id)

    if request.method == "POST":
        quitRequest = utils.quitRequest(member=profile, group=group)
        if quitRequest:
            messages.success(request, f"Your quit request had been sent to the host.")
        else:
            messages.error(request, f"You've already sent the quit application, please wait for the host to accept your request.")
        
        return redirect('account')
    
    context = {
        "group": group,
    }
    return render(request, 'projects/delete-template.html', context=context)
        


@login_required(login_url="login")
def apply(request, pk):
    project = Project.objects.get(id=pk)
    applier = request.user.profile
    newApp = utils.checkApplication(applier, project)

    if newApp:
        messages.success(request, "Your application has been sent to the project host.")
    else:
        messages.error(request, "You've applied for the project before.")
    
    return redirect('project', pk=project.id)



@login_required(login_url='login')
def applyBox(request):
    profile = request.user.profile
    group = Group.objects.get(id=profile.group_id)

    applyRequests = Application.objects.distinct() \
                            .filter( group=group, is_apply=True )
    
    quitRequests = Application.objects.distinct() \
                            .filter( group=group, is_apply=False )
    context = {
        "applyRequests":applyRequests,
        "quitRequests": quitRequests,
        "project":group.project,
    }

    return render(request, 'projects/apply-box.html', context=context)


@login_required(login_url='login')
def verifyApply(request, pk):
    application = Application.objects.get(id=pk)
    group = application.group
    applier = application.sender
    host = group.project.owner

    if request.method == "POST":
        decision = request.POST.get('decision')
        if decision == 'reject':
            subject = 'Application Declined'
            body = f'This message is sent by System.\nSorry, your application for porject {group.project} was declined by the host'
            messages.success(request, f"You've declined the {applier}'s application")

        else:
            # Check Whether the applier is already in a project
            if applier.group_id:
                subject = 'Application Error'
                body = f"Your Application for {group.project} was failed because yor're already in other project."
                messages.info(request, f"The applier {applier} has already attend other project")
            
            # Check whether the group is full
            elif group.is_full:
                subject = 'Application Error'
                body = f"The project: {group.project} you applied is already full"
                messages.info(request, "Your project team is already full.")
            
            else:
                group.addMember(applier)
                applier.group_id = group.id
                applier.save()
                subject = "Application Accepted"
                body = f"Congratulation! Your application for project {group.project} was accepted by the host!"
                messages.success(request, f"You've accept {applier} application as your team member.")

        utils.NotificationMessage(
            recipient = applier,
            sender = host,
            subject = subject,
            body = body,
            is_apply_related = True,
        ) 

        application.delete()
        return redirect('apply-box')

    context={
        'apply':application,
    }
    return render(request, 'projects/verify-apply.html', context=context)


@login_required(login_url='login')
def verifyQuit(request, pk):
    quitRequest = Application.objects.get(id=pk)

    if request.method == "POST":
        decision = request.POST.get('decision')
        if decision == 'reject':
            messages.success(request, f"You've REJECTED the quit request from member: {quitRequest.sender}")
            subject = "Quit Request Rejected"
            body = "This Message is sent by system.\nYour quit request has been REJECTED by the host."
            
        
        elif decision == "confirm":
            messages.success(request, f"You've ACCEPTED the quit request from member: {quitRequest.sender}")
            subject = "Quit Request Confirmed"
            body = "This Message is sent by system.\nYour quit request has been ACCEPTED by the host, go to join another project group!"
            quitRequest.group.removeMember(quitRequest.sender)

        

        utils.NotificationMessage(
            sender = request.user.profile,
            recipient = quitRequest.sender,
            subject = subject,
            body = body,
            is_apply_related = True,
        )

        quitRequest.delete()
        return redirect('apply-box')

    context = {
        'quitRequest': quitRequest,
    }

    return render(request, "projects/verify-quit.html", context=context)

projects/templates/projects/apply-box.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
Apply box
{% endblock %}

{% block content %}
<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">Application for {{ project }}</h3>

    {% if applyRequests %}
    <ul class="messages">
      {% for apply in applyRequests %}
      <li class="message message--unread">

        <a href="{% url 'verify-apply' apply.id %}">
          <span class="message__author">{{apply.sender.username}}</span>
          <span class="message__date">{{apply.created}}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <table class="settings__table">
      <tr>
            <td class="settings__thumbnail">
              <a href="#"><img src="{% static 'images/no-application.jpg' %}" alt='no apply'/></a>
            </td>
            <td class="settings__tableInfo">
              <h5>You havn't received any application yet.</h5>
            </td>
          </tr>
    </table>
    {% endif %}

    <br/><br><hr/><br>

    <h3 class="inbox__title">Project Quit Request</h3>
    
    {% if quitRequests %}
    <ul class="messages">
      {% for quit in quitRequests %}
      <li class="message message--unread">
        <a href="{% url 'verify-quit' quit.id %}">
          <span class="message__author">{{quit.sender.username}}</span>
          <span class="message__date">{{quit.created}}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <table class="settings__table">
      <tr>
            <td class="settings__thumbnail">
              <a href="#"><img src="{% static 'images/quit-request.jpg' %}" alt='quit request'/></a>
            </td>
            <td class="settings__tableInfo">
              <h5>You havn't received any QUIT request yet.</h5>
            </td>
          </tr>
    </table>
    {% endif %}

  </div>
</main>

{% endblock content %}

projects/templates/projects/delete-template.html
<!-- delete_template.html -->
{% extends 'main.html' %}

{% block title %}
delete Project
{% endblock %}

{% block content %}
    




    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    <p>Are your sure you want to 
                        {% if member %}
                        <strong>REMOVE Member: {{ member }}</strong>?
                        {% elif project %}
                        <strong>DELETE Project: {{ project }}</strong>?
                        {% elif group %}
                        <strong>QUIT group of Project: {{ group.project }}</strong>?
                        {% endif %}
                    </p>
                    <a class="btn btn--sub btn--lg  my-md" href="{{ request.GET.next }}">&#x2190 Go Back</a>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Confirm" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}

projects/templates/projects/project.html
{% extends 'main.html' %}

{% block title %}
{{project.title}}
{% endblock %}

{% block content %}
    <!-- Main Section -->
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        

        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{ project.imageURL }}" alt="portfolio thumbnail" />
          <h2 class="singleProject__title">{{ project.title }}</h2>

          <!-- project Host table -->
          <h3 class="singleProject__subtitle">Host</h3>
          <table class="settings__table">
            <!-- Host -->
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'user-profile' project.owner.id %}"><img src="{{ project.owner.imageURL }}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'user-profile' project.owner.id %}">{{ project.owner.username }}</a>
                <p>
                  {{ project.owner.bio|slice:'50' }}
                </p>
              </td>
              <td class="settings__tableActions">
                {% if project.owner != request.user.profile  %}
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'create-message' project.owner.id %}?next={{ project.id }}" ><i class="im im-edit"></i>Message</a>
                {% endif %}
                {% if not request.user.profile.group_id and not project.group.is_full %}
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'apply' project.id %}" ><i class="im im-edit"></i>Apply</a>
                {% endif %}
              </td>
            </tr>
          </table>
          <!--End of project Host table -->



          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            {{ project.description }}
          </div>
          <!-- <a href="{% url 'update-project' project.id %}">Edit Project</a> -->
        </div>

        <!-- Module part -->
        <div class="column column--1of3">

          <h3 class="singleProject__subtitle">Project Feature</h3>
          <div class="singleProject__toolStack">
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{ project.get_feature_display }}</small>
            </span>
          </div>

          <h3 class="singleProject__subtitle">Project Type</h3>
          <div class="singleProject__toolStack">
            {% for type in project.types.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{ type }}</small>
            </span>
            {% endfor %}
          </div>

          <h3 class="singleProject__subtitle">Involved Modules</h3>
          <div class="singleProject__toolStack">
            {% for module in project.modules.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{module}}</small>
            </span>
            {% endfor %}
          </div>

        </div>
          <!-- End of Module -->

        

      </div>
    </div>
    </div>
  </main>
{% endblock %}

projects/templates/projects/project_form.html
{% extends 'main.html' %}

{% block title %}
Project Form
{% endblock %}

{% block content %}
<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" 
                  method='POST' 
                  enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>
                <br>
                {% endfor %}


                <div class="form__field">
                    <label for="formInput#text">Module</label>
                    <textarea class="input" 
                              name="newmodules" 
                              placeholder="Add tags here..."></textarea>
                </div>

                <div class='form__field'>
                    {% for module in project.modules.all %}
                        <div class='project-tag tag tag--pill tag--main' 
                             data-module="{{ module.id }}"
                             data-project="{{ project.id }}">
                                {{module.name}} &#215;
                        </div>
                    {% endfor %}
                </div>

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>


{% endblock %}

projects/templates/projects/projects.html
{% extends 'main.html' %}

{% block title %}
Project List
{% endblock %}

{% block content %}

    <main class="projects">

    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>
        
        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'projects' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                     value = "{{ search_query }}"
                     placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">

        {% for proj in projects %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'project' proj.id %}" class="project">
                <img class="project__thumbnail" src="{{ proj.imageURL }}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{proj.title}}</h3>
                  <p><a class="project__author" href="{% url 'user-profile' proj.owner.id %}">By {{proj.owner}}</a></p>
                  
                  <div class="project__tags">
                    {% for module in proj.Modules.all %}
                    <span class="tag tag--pill tag--main">
                      <small>{{ module }}</small>
                    </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
        {% endfor %}

        </div>
      </div>
    </section>

    {% include 'pagination.html' with queryset=projects custom_range=custom_range %}

  </main>

{% endblock %}

projects/templates/projects/verify-apply.html
{% extends 'main.html' %}

{% block title %}
Verify Application
{% endblock %}

{% block content %}

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'apply-box' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    <p>Do you want to invite <strong>{{ apply.sender }}</strong> as a project member?</p>
                    <br/>
                    <label><input class="input" type="radio" name="decision" value="confirm">Yes</label><br/>
                    <label><input class="input" type="radio" name="decision" value="reject">No</label><br/>
                    
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Confirm" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}

projects/templates/projects/verify-quit.html
{% extends 'main.html' %}

{% block title %}
Verify Quit Requests
{% endblock %}

{% block content %}

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'apply-box' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}
                    <p> 
                        Do you accept the 
                        <strong>QUIT request</strong> 
                        from your project menber: <strong>{{ quitRequest.sender }}</strong>?</p>
                    <br/>
                    <label><input class="input"  type="radio" name="decision" value="confirm">Yes</label><br/>
                    <label><input class="input" type="radio" name="decision" value="reject">No</label><br/>
                    
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Confirm" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}